
services:
  store:
    image: "postgres:15.1"
    ports:
      - 5432:5432
    command: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE:
      POSTGRES_PASSWORD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DATABASE "]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./_volumes/store:/var/lib/postgresql/data
    networks:
      - local


  socket_api:
    build: ./images/socket_api
    image: "$OWNER/jef_socket_api:$VERSION"
    command: ["npm", "run", "start"]
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD:
      POSTGRES_HOST: localhost
      OLLAMA_HOST: localhost
      FILESTORE_HOST: localhost
      TRANSLATE_HOST: localhost
      SAVE_LOCATION: /home/ai-game-server/Documents/server-JEF/_volumes/images/
      FAST:
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    expose:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      store:
        condition: service_healthy
    volumes:
      - ./images/socket_api/src:/usr/app/src
    network_mode: host
      

  filestore:
    build: ./images/filestore
    image: "$OWNER/jef_filestore:$VERSION"
    command: ["npm", "run", "dev"]
    restart: always
    ports:
      - 3030:3000
    expose:
      - 3030:3000
    volumes:
      - ./images/filestore/src:/usr/app/src
      - ./_uploads:/usr/app/uploads
      - ./_volumes/images:/usr/app/generations
    networks:
      - local


  ollama:
    image: "ollama/ollama:latest"
    ports:
      - 11434:11434
    volumes:
      - ./_models/ollama:/root/.ollama
    networks:
      - local
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  libretranslate:                    
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    hostname: libretranslate
    restart: "always"
    user: root
    ports:
      - 7500:5000
    environment:
      LT_DEBUG: true
      LT_LOAD_ONLY: 'nl,fr,en'
      LT_DISABLE_WEB_UI: true
      LT_WITH_MODELS: true 
      LT_THREADS: 2
      LT_SUGGESTIONS: false 
    tty: true 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      start_period: "60s"
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    volumes:
      - ./_volumes/libretranslate/data:/home/libretranslate/.local/share
      - ./_volumes/libretranslate/cache:/home/libretranslate/.local/cache
      - ./_volumes/libretranslate/libretranslate_models:/home/libretranslate/.local:rw
      - ./_volumes/libretranslate/all:/home/libretranslate:rw
      
  

networks:
  local:
    driver: bridge
    
