
services:
  store:
    image: "postgres:15.1"
    ports:
      - 5432:5432
    command: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE:
      POSTGRES_PASSWORD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DATABASE "]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./_volumes/store:/var/lib/postgresql/data
    networks:
      - local


  socket_api:
    build: ./images/socket_api
    image: "$OWNER/jef_socket_api:$VERSION"
    command: ["npm", "run", "dev"]
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD:
      POSTGRES_HOST: localhost
      OLLAMA_HOST: localhost
      FILESTORE_HOST: localhost
      TRANSLATE_HOST: localhost
    ports:
      - 3000:3000
    expose:
      - 3000:3000
    depends_on:
      store:
        condition: service_healthy
    volumes:
      - ./images/socket_api/src:/usr/app/src
    network_mode: host
      

  filestore:
    build: ./images/filestore
    image: "$OWNER/jef_filestore:$VERSION"
    command: ["npm", "run", "dev"]
    restart: always
    ports:
      - 3030:3000
    expose:
      - 3030:3000
    volumes:
      - ./images/filestore/src:/usr/app/src
      - ./_uploads:/usr/app/uploads
      - ./_volumes/images:/usr/app/generations
    networks:
      - local


  ollama:
    image: "ollama/ollama:latest"
    ports:
      - 11434:11434
    volumes:
      - ./_models/ollama:/root/.ollama
    networks:
      - local
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  libretranslate:                    
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    hostname: libretranslate
    restart: "no"
    ports:
      - 7500:5000
    environment:
      LT_DEBUG: true
      LT_FRONTEND_LANGUAGE_SOURCE: de
      LT_FRONTEND_LANGUAGE_TARGET: en
      LT_LOAD_ONLY: 'nl,fr,en'
      LT_THREADS: 4
      LT_SUGGESTIONS: true  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  mqtt:
    driver: bridge

  local:
    driver: bridge
    
