
const locations = [
  "Dense Jungle",
  "Deep Sea",
  "Mysterious Cave",
  "Volcanic Island",
  "Desert Oasis",
  "Snowy Mountain",
  "Ancient Temple",
  "Floating Island",
  "Underground City",
  "Sky Kingdom",
  "Haunted Forest",
  "Magical Castle",
  "Enchanted Garden",
  "Candy Land",
  "Toy Factory",
  "Space Station",
  "Alien Planet",
  "Moon Base",
  "Underwater City",
  "Fairy Tale Village",
  "Pirate Ship",
  "Forgotten Ruins",
  "Crystal Cavern",
  "Robot Factory",
  "Steampunk City",
  "Medieval Village",
  "Royal Palace",
  "Witch's Cottage",
  "Dinosaurs' Valley",
  "Rainbow Bridge",
  "Cloud City",
  "Hidden Lagoon",
  "Mystic Swamp",
  "Clock Tower",
  "Fantasy Library",
  "Secret Laboratory",
  "Magical School",
  "Time Traveler's Base",
  "Atlantis",
  "Treehouse Village",
  "Giant's Castle",
  "Dragon's Lair",
  "Lunar Crater",
  "Starry Galaxy",
  "Frozen Wasteland",
  "Tropical Paradise",
  "Futuristic Metropolis",
  "Post-Apocalyptic City",
  "Subterranean Tunnel Network",
  "Carnival",
  "Wild West Town",
  "Ancient Marketplace",
  "Arabian Palace",
  "Floating Balloon City",
  "Giant Mushroom Forest",
  "Crystal Lake",
  "Shadow Realm",
  "Fire Realm",
  "Water Realm",
  "Earth Realm",
  "Wind Realm",
  "Outer Dimension",
  "Parallel Universe",
  "Virtual Reality World",
  "Arcade World",
  "Secret Base",
  "Train Station in the Clouds",
  "Zany Zoo",
  "Giant Board Game",
  "Puzzle Land",
  "Coral Reef",
  "Sunken Shipwreck",
  "Fantasy Farm",
  "Mirror World",
  "Astral Plane",
  "Legendary Battlefield",
  "Epic Carnival",
  "Robot City",
  "Space Carnival",
  "Ice Palace",
  "Volcanic Fortress",
  "Lush Savannah",
  "Meteor Crater",
  "Giant's Playground",
  "Clockwork City",
  "Whimsical Bakery",
  "Crystal Observatory",
  "Hidden Treasure Cove"
];