
const timePeriods = [
  "Prehistoric Era",
  "Stone Age",
  "Ice Age",
  "Bronze Age",
  "Iron Age",
  "Ancient Egypt",
  "Ancient Mesopotamia",
  "Ancient Greece",
  "Ancient Rome",
  "Viking Age",
  "Medieval Europe",
  "Feudal Japan",
  "Renaissance",
  "Age of Exploration",
  "Colonial America",
  "Industrial Revolution",
  "Victorian Era",
  "Wild West",
  "World War I",
  "Roaring Twenties",
  "World War II",
  "1950s Americana",
  "1960s Space Race",
  "1970s Disco Era",
  "1980s Retro Wave",
  "1990s Digital Revolution",
  "Modern Day",
  "Near Future",
  "Distant Future",
  "Post-Apocalyptic Future",
  "Cyberpunk Future",
  "Steampunk Alternate History",
  "Dieselpunk Alternate History",
  "Underwater Civilization Era",
  "Sky Kingdom Era",
  "Fantasy Medieval Era",
  "Magical Ancient Egypt",
  "Sci-Fi Roman Empire",
  "Alien Invasion Era",
  "Robot Uprising Era",
  "Time-Travel Mashup",
  "Jurassic Period",
  "Cretaceous Period",
  "Mythological Greece",
  "Atlantis Era",
  "Dinosaur Adventure Era",
  "Fantasy Ice Age",
  "Pirate Golden Age",
  "Revolutionary War Era",
  "Ancient Chinese Dynasties",
  "Arabian Nights Era",
  "Prehistoric Fantasy",
  "Celestial Epoch",
  "Galactic Empire Era",
  "Lost World Era",
  "Dark Ages",
  "Age of Mythology",
  "Golden Age of Pirates",
  "New World Expeditions",
  "World's Fair Era",
  "Noah's Ark Era",
  "Underworld Journey Era",
  "Dream World Era",
  "Fairy Tale Kingdom",
  "Cosmic Origin Epoch",
  "Quantum Future",
  "Astral Plane Era",
  "Virtual Reality Age",
  "Time of Legends",
  "Future Utopia",
  "Neo-Medieval Age",
  "Parallel Universes",
  "Hidden Kingdoms of Earth",
  "Interstellar Migration Era"
];